# describes a Kubernetes deployment of the ike091/telegraf container

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "telegraf.fullname" . }}
  labels:
    app: {{ template "telegraf.name" . }}
    chart: {{ template "telegraf.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "telegraf.name" . }}
      instance: {{ .Values.Instance | quote }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "telegraf.name" . }}
        chart: {{ template "telegraf.chart" . }}
        instance: {{ .Values.Instance | quote }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: telegraf
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}

          volumeMounts:
            - mountPath: /etc/config
              name: telegraf-volume 

          ports:
            - containerPort: 161

      volumes:
        - name: telegraf-volume
          # populate volume with config map data
          configMap:
            name: telegraf-{{ .Values.Instance }}-configuration
