apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       - name: telegraf
          image: ike091/telegraf:latest
          ports:
          - containerPort: 80
